# Generated by Django 3.2.19 on 2023-06-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='our_story',
            field=models.TextField(blank=True),
        ),
    ]
