# Generated by Django 3.2.19 on 2023-06-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20230620_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('ST', 'Starters'), ('PI', 'Pizza'), ('PA', 'Pasta')], default='ST', max_length=2),
        ),
    ]
