# Generated by Django 3.2.19 on 2023-06-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20230621_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='table',
            new_name='tables',
        ),
    ]
