# Generated by Django 3.2.19 on 2023-06-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_rename_table_booking_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=4),
        ),
    ]
