# Generated by Django 3.2.19 on 2023-06-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_table_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_phone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
